// Frases célebres de José María García, para rematar el mensaje que se publica
// en el chat cada vez que termina una fase del torneo. Solo el texto de la cita;
// la atribución la añade notify.mjs. Fuente: https://citas.in/autores/jose-maria-garcia/
export const GARCIA_QUOTES = [
  "Abrazafarolas, chupópteros, correveidiles, mustélidos, estómagos agradecidos…",
  "Ni una mala palabra, ni una buena acción.",
  "¡Maricón el último!",
  "Muy buenas noches y saludos cordiales.",
  "Lo más redondo que ha visto en su vida es una palangana.",
  "Ramón Mendoza Fontela: el mandamal del pelo blanco.",
  "Son más de treinta años en esta bendita profesión, cantando y contando las verdades del barquero.",
  "Soy católico a pesar de la Conferencia Episcopal. Porque la fe no la voy a perder pero me han quitado la afición.",
  "Estamos curados y vacunados de no pocos espantos.",
  "Ojo al dato.",
  "Esto es de juzgado de guardia.",
  "Ramón Mendoza no es que dejara al Real Madrid hecho un solar…¡es que se llevó hasta el solar!",
  "Uno es esclavo de sus palabras y dueño de sus silencios.",
  "Al final llego a una conclusión aterradora: o hay dos Españas, o yo he desayunado whisky en vez de fruta.",
  "A los grandes, el culo. A los pequeños, porrrr el culo.",
  "Eso no se le ocurre ni al que asó la manteca.",
  "La Quinta del Buitre es el timo de la estampita.",
  "Miguel González del Campo, Míchel: a esparragar, muñeco.",
  "Michel, 300 millones por tirar los corners.",
  "Se lo pasan por el forro de sus caprichos.",
  "Soy el que les canta y les cuenta las verdades del barquero.",
  "Esto es para caducos y trasnochados.",
  "Aquí, hasta el más tonto hace relojes…¡y encima, andan!",
  "Lo peor no es perder: es la cara de gilipollas que se te queda.",
  "El imperio del monopolio.",
  "Ellos van en un transatlántico mientras nosotros navegamos en un tirachinas.",
  "El tiempo es ese juez insobornable que da y quita razones.",
  "El rumor es la antesala de la noticia.",
  "En rigurosa primicia informativa.",
  "Esto es de tribuletes de pesebre.",
  "No es lo mismo un hombre pobre que un pobre hombre.",
  "El halago debilita.",
  "¡Para la cinta!",
  "Por activa y por pasiva.",
  "Beberse hasta el agua de los floreros.",
  "¿Lo mejor del partido? ¿Lo menos bueno? ¿El árrrbitro?",
  "Boooooooooooomba informativa.",
  "El sí está al alcance de cualquier gilipollas. Lo más difícil es decir no.",
  "Hortaleza, porros y cerveza.",
];

// Una frase al azar. ponytail: Math.random basta; no hace falta PRNG sembrado.
export const randomQuote = () => GARCIA_QUOTES[Math.floor(Math.random() * GARCIA_QUOTES.length)];
